language: ruby
rvm:
 - 2.5.9

addons:
 postgresql: "9.4"

before_script:
 - gem update --system
 - gem --version
 - gem install bundler:2.2.2
 - psql -c 'create database ziher_test;' -U postgres
 - bundle exec rake db:migrate

